# Generated by Django 3.0.7 on 2020-07-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=64, verbose_name='订单号')),
                ('order_date', models.DateField(verbose_name='下单日期')),
                ('deliver_date', models.DateField(verbose_name='交付日期')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('memo', models.TextField(blank=True, default='', verbose_name='备注')),
                ('contact', models.CharField(blank=True, default='', max_length=32, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='电话')),
                ('fax', models.CharField(blank=True, default='', max_length=32, verbose_name='传真')),
                ('deliver_address', models.CharField(blank=True, default='', max_length=128, verbose_name='交付地址')),
                ('invoice_type', models.CharField(blank=True, default='', max_length=64, verbose_name='发票类型')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='金额')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='优惠额')),
                ('status', models.CharField(choices=[('0', '新订单'), ('1', '在生产'), ('4', '丢弃'), ('9', '已批准'), ('99', '已出库')], default='0', max_length=16, verbose_name='状态')),
                ('sale_man', models.CharField(blank=True, max_length=32, null=True, verbose_name='业务员')),
                ('partner', models.ForeignKey(limit_choices_to={'partner_type': 'C'}, on_delete=django.db.models.deletion.PROTECT, to='basedata.Partner', verbose_name='客户')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '销售订单',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(choices=[('kg', '千克'), ('ge', '个'), ('gal', '加仑'), ('ratio', '比率')], default='kg', max_length=16, verbose_name='计量单位')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='数量')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='售价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deliver_date', models.DateField(verbose_name='交付日期')),
                ('status', models.BooleanField(default=0, verbose_name='状态')),
                ('memo', models.TextField(blank=True, default='', verbose_name='备注')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.SaleOrder')),
                ('material', models.ForeignKey(blank=True, limit_choices_to={'can_sale': '1', 'is_virtual': '0'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='basedata.Material', verbose_name='产品')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
            },
        ),
    ]
