# Generated by Django 3.0.7 on 2020-07-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=32, verbose_name='代码')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='名称')),
                ('short', models.CharField(blank=True, default='', max_length=64, verbose_name='简称')),
                ('partner_type', models.CharField(choices=[('C', '客户'), ('S', '供应商')], default='C', max_length=16, verbose_name='类别')),
                ('level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='C', max_length=16, verbose_name='等级')),
                ('tax_num', models.CharField(blank=True, default='', max_length=64, verbose_name='纳税识别号')),
                ('tax_address', models.CharField(blank=True, default='', max_length=128, verbose_name='开票地址')),
                ('tax_account', models.CharField(blank=True, default='', max_length=64, verbose_name='发票开户行')),
                ('contacts', models.CharField(blank=True, default='', max_length=64, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='联系电话')),
                ('memo', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '合作伙伴',
                'verbose_name_plural': '合作伙伴',
                'permissions': (('view_all_customer', '查看所有客户'), ('view_all_supplier', '查看所有供应商')),
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='代码')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.MaterialCategory', verbose_name='父类')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='材料代码')),
                ('barcode', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='条形码')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='材料名称')),
                ('spec', models.CharField(blank=True, default='', max_length=120, verbose_name='规格')),
                ('status', models.BooleanField(default=True, verbose_name='是否在用')),
                ('is_equip', models.BooleanField(default=False, verbose_name='是否设备')),
                ('can_sale', models.BooleanField(default=True, verbose_name='可销售')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='虚拟')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basedata.MaterialCategory', verbose_name='类别')),
            ],
            options={
                'verbose_name': '材料',
                'verbose_name_plural': '材料',
                'ordering': ['-id'],
            },
        ),
    ]
