# Generated by Django 3.0.7 on 2020-07-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basedata', '0001_initial'),
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='development.Formula', verbose_name='配方'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('code', 'name', 'spec')},
        ),
    ]
