# Generated by Django 3.0.7 on 2020-07-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='配方名称')),
                ('version', models.CharField(blank=True, default='', max_length=32, verbose_name='配方版本')),
                ('per_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='每份重量')),
                ('status', models.CharField(choices=[('OFFICIAL', '正式'), ('TEST', '中试'), ('PAUSE', '待确认'), ('DEV', '开发'), ('INVALID', '作废')], default='DEV', max_length=16, verbose_name='状态')),
                ('processing_way', models.CharField(choices=[('MAKE', '制造'), ('PACKAGE', '组装'), ('SPLIT', '分装')], default='PACKAGE', max_length=16, verbose_name='加工方式')),
                ('authors', models.CharField(blank=True, max_length=64, null=True, verbose_name='开发负责人')),
                ('memo', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('history', models.TextField(blank=True, null=True, verbose_name='修改历史')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basedata.MaterialCategory', verbose_name='类别')),
            ],
            options={
                'verbose_name': '配方',
                'verbose_name_plural': '配方',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FormulaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.CharField(blank=True, default='', max_length=64, verbose_name='车间')),
                ('measure', models.CharField(choices=[('kg', '千克'), ('ge', '个'), ('gal', '加仑'), ('ratio', '比率')], default='kg', max_length=16, verbose_name='计量单位')),
                ('value_type', models.CharField(choices=[('STR', 'STRING'), ('NUM', 'NUMBER'), ('RATIO', 'RATIO')], default='NUM', max_length=16, verbose_name='数据类型')),
                ('value', models.CharField(blank=True, default='', max_length=64, verbose_name='数据值')),
                ('memo', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.Formula', verbose_name='配方')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedata.Material', verbose_name='物料')),
            ],
            options={
                'verbose_name': '配方成分',
                'verbose_name_plural': '配方成分',
                'ordering': ['workshop'],
            },
        ),
    ]
