# Generated by Django 3.0.7 on 2020-07-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('execute_time', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '库存索引',
                'verbose_name_plural': '库存索引',
            },
        ),
        migrations.CreateModel(
            name='MinimumInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('execute_time', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('product_date', models.DateTimeField(verbose_name='生产日期')),
                ('measure', models.CharField(choices=[('kg', '千克'), ('ge', '个'), ('gal', '加仑'), ('ratio', '比率')], default='kg', max_length=16, verbose_name='计量单位')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='数量')),
                ('batch', models.CharField(blank=True, default='', max_length=32, verbose_name='批号')),
                ('type', models.SmallIntegerField(choices=[(1, '产品进仓'), (2, '待转成'), (3, '改标进仓'), (4, '+调整库存'), (5, '成转待'), (6, '销售'), (7, '-调整库存')], default=1, verbose_name='业务类别')),
                ('memo', models.TextField(blank=True, default='', verbose_name='备注')),
                ('material', models.ForeignKey(blank=True, limit_choices_to={'is_virtual': '0'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='basedata.Material', verbose_name='物料')),
            ],
            options={
                'verbose_name': '产品流水',
                'verbose_name_plural': '产品流水',
            },
        ),
        migrations.CreateModel(
            name='MinimumInventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(choices=[('kg', '千克'), ('ge', '个'), ('gal', '加仑'), ('ratio', '比率')], default='kg', max_length=16, verbose_name='计量单位')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='数量')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.MinimumInventory')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Material', verbose_name='物料')),
            ],
            options={
                'verbose_name': '最低库存',
                'verbose_name_plural': '最低库存',
            },
        ),
        migrations.CreateModel(
            name='InventoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(choices=[('kg', '千克'), ('ge', '个'), ('gal', '加仑'), ('ratio', '比率')], default='kg', max_length=16, verbose_name='计量单位')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='数量')),
                ('batch', models.CharField(blank=True, default='', max_length=32, verbose_name='批号')),
                ('product_date', models.DateTimeField(verbose_name='生产日期')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.Inventory')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedata.Material', verbose_name='物料')),
            ],
            options={
                'verbose_name': '库存信息',
                'verbose_name_plural': '库存信息',
                'ordering': ['material'],
            },
        ),
    ]
